# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serving',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4),
            preserve_default=False,
        ),
    ]
