# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_serving_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='vegetarian',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
