# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_dish_vegetarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serving',
            name='canteen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servings', to='base.Canteen'),
        ),
        migrations.AlterField(
            model_name='serving',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servings', to='base.Dish'),
        ),
    ]
