# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20161123_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='serving',
            name='price_staff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
