# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('vegetarian', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Serving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price_staff', models.DecimalField(decimal_places=2, max_digits=4)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servings', to='canteen.Canteen')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servings', to='canteen.Dish')),
            ],
        ),
    ]
