# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serving',
            name='deprecated',
            field=models.BooleanField(default=False),
        ),
    ]
