# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0005_auto_20161125_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serving',
            old_name='deprecated',
            new_name='officially_deprecated',
        ),
    ]
