# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0006_auto_20161125_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='serving',
            name='official',
            field=models.BooleanField(default=True),
        ),
    ]
