# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 19:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('canteen', '0007_serving_official'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServingVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter', models.BooleanField(default=False)),
                ('serving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='canteen.Serving')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serving_verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='servingverification',
            unique_together=set([('serving', 'user')]),
        ),
    ]
