# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 16:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('canteen', '0009_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set([('user', 'pattern')]),
        ),
    ]
