# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0010_auto_20161127_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='last_notified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
