# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0011_notification_last_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='serving',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
