# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 17:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('canteen', '0012_serving_notified'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanteenUserConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=100)),
                ('hidden', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canteen_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
