# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0013_canteenuserconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_times', to='canteen.Canteen')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='openingtime',
            unique_together=set([('canteen', 'weekday')]),
        ),
    ]
